language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libboost1.54-test-dev
script:
- cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBoost_DEBUG=ON
- cmake .
- cmake --build .
- cmake --build . --target package
- sudo dpkg -i print_ip-*.deb && pwd && ls -l
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u libhet:$BINTRAY_API_KEY "https://api.bintray.com/content/libhet/OTUS_CPP/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
