language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install graphviz
- sudo apt-get install doxygen
- sudo apt-get install libboost-test-dev
script:
- cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBoost_DEBUG=ON
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- sudo dpkg -i print_ip-*.deb && pwd && ls -l
- doxygen Doxyfile
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u libhet:$BINTRAY_API_KEY "https://api.bintray.com/content/libhet/OTUS_CPP/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip-cleanup: true
    local_dir: html/
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      branch: master